### ISSUE TITLE
Invalid parameters in request to certificate service: Sorry, there is something invalid in your request. Error Validating with Schema #/v/0: 2 schema violations found

### ISSUE THREAD

**Issue by ManuelB** [ere-health/dgc-ps-app#23]
# Enter http://localhost:8080/api/certify/v2/issue?fn=Manuel&gn=Blechschmidt&dob=1986-07-16&id=BSNR-ARZT&tg=840539006&vp=11193050005&mp=EU/1/20/1528&ma=ORG-100030215&dn=1&sd=1&dt=2021-07-13

Expected:
 * Should work

Actually:
![Screenshot from 2021-06-16 19-30-56](https://user-images.githubusercontent.com/457641/122265910-80db1a80-ced9-11eb-88f8-691c3e0243a1.png)

{
code: 100400,
message: "Invalid parameters in request to certificate service: Sorry, there is something invalid in your request. Error Validating with Schema #/v/0: 2 schema violations found"
}

**Comment by tempuser5432** [comment]
Are you sure, the `/` in the `mp` param is properly encoded?

**Comment by tempuser5432** [comment]
It should be. I will extend the logs. Is there an option to test this without access to the TI?

**Comment by tempuser5432** [comment]
Observations:
1. the `id` param may only contain `A-Z0-9`, i.e. `BSNR-ARZT` is invalid
2. `gn` and `fn` seem to be mixed up (this should cause no validation error however)
3. `sd` should be `2`
4. `vp` should be `1119349007` (the other parameters indicate the BioNTech vaccine)

**Comment by tempuser5432** [comment]
Confirmed to be working in RU with current `main` branch.
