### ISSUE TITLE
Remove non-schema parameters from `V` class

### ISSUE THREAD

**Issue by tempuser5432** [ere-health/dgc-ps-app#38]
The fields `co`, `is`, `ci` in the DTO-class `V` are not part of the official specification and should be removed. The same holds for the `ver` field in `VaccinationCertificateRequest`.

Since `id` is set by the request, the UUID-generation should be removed as well.

**Comment by ManuelB** [comment]
@tempuser5432 I received a schema error when I did not transmit the co, is, and ci field to the service. Feel free to remove them and try the service in the RU.

**Comment by tempuser5432** [comment]
This happens now for the recovery certificate (if they are not sent, the RU reports a schema validation error).
