### ISSUE TITLE
Support Basic Auth for connector web service calls

### ISSUE THREAD

**Issue by ManuelB** [ere-health/dgc-ps-app#53]
`
Service s = new Service();
Port port = s.getPort();

BindingProvider prov = (BindingProvider)port;
prov.getRequestContext().put(BindingProvider.USERNAME_PROPERTY, "myusername");
prov.getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, "mypassword");

port.call();
`

**Comment by tempuser5432** [comment]
This only needs to be added to `EndpointDiscoveryService.configureSSLTransportContext`.

**Comment by tempuser5432** [comment]
Does the `connector.sds`-endpoint also need basic auth?

**Comment by ManuelB** [comment]
@tempuser5432 I don't think so. Can we just add a configuration parameter to enable it and set it by default to false?

**Comment by tempuser5432** [comment]
Ok.
