### ISSUE TITLE
Datenschutzfolgeabschätzung

### ISSUE THREAD

**Issue by tempuser5432** [ere-health/dgc-ps-app#75]
Es soll eine Datenschutzfolgeabschätzung gemäß §35 DSGVO für den Bereich der Übertragnung der Impfpersonendaten erstellt werden.

Diese soll in `doc/DSFA.md` hinzugefügt werden.

**Comment by tempuser5432** [comment]
Inhalt:
1. Beschreibung der Art der Datenverarbeitung
2. Begründung der Datenerhebung
2. Beschreibung, welche Daten erhoben werden
 ** Hinweis darauf, dass nur die minimal notwendigen Daten erhoben werden
3. Beschreibung, welche Daten gespeichert werden (keine) und wie lange (n/a)
4. Beschreibung der Maßnahmen zur Wahrung der Vertraulichkeit der Daten
 ** auch technische Beschreibungen
5. Beschreibung der möglichen Risiken
6. Bewertung der Risiken (Eintrittswahrscheinlichkeit, Schadenshöhe)

**Comment by tempuser5432** [comment]
@ManuelB ist hier auch der Auth-Prozess relevant? Das obige betrachtet nur die Übermittlung der Impfdaten.

**Comment by ManuelB** [comment]
Potentiell kann der JWT Token Daten des Ausstellenden enthalten. Also wir sollten das mal mit aufnehmen, da die Daten aber in jedem Telefonbuch stehen und auch von der KBV veröffentlich werden, halte ich das für unproblematisch. Allerdings sollte der JWT Token nicht verloren gehen.
