### ISSUE TITLE
Use relative paths for API location in forms

### ISSUE THREAD

**Issue by tempuser5432** [ere-health/dgc-ps-app#9]
Since the resulting `.war`-file may be deployed in context folder, its location in the `fetch` calls of the frontend should be made relative.

This affects both `covid-19-certificates.html` and `covid-19-recovered-certificate.html`.

**Comment by richard-infai** [comment]
The request path in the html files is relative to the host.

**Comment by tempuser5432** [comment]
But is it relative to the path?
